### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by asmeurer** [deshaw/versioned-hdf5#10]
We need to support Python 2 for now.

**Comment by ArvidJB** [comment]
How much less work would it be if we make `versioned_hdf5` *importable* only from Python 2? In that case we can restrict using it to the vast majority of our users who are already on Python 3, but the subset of legacy jobs that is still in Python 2 will at least not break on
```import versioned_hdf```

**Comment by quarl** [comment]
If we only want to read the latest version (from py2 or otherwise), do we need to use versioned_hdf5 for a file written with versions?

**Comment by asmeurer** [comment]
> How much less work would it be if we make versioned_hdf5 importable only from Python 2? In that case we can restrict using it to the vast majority of our users who are already on Python 3, but the subset of legacy jobs that is still in Python 2 will at least not break on

This would be doable, but I'm unclear exactly what the behavior should be. What should happen if someone tries to use something from `versioned_hdf5`?

> If we only want to read the latest version (from py2 or otherwise), do we need to use versioned_hdf5 for a file written with versions?

You could just read the data directly from the `_versioned_data/version-name` group in the file.

**Comment by quarl** [comment]
Ok.  I think we could live with no py2 support.  We can make the import lazy, so that versioned_hdf5 (& ndindex) only get imported when needed.
In that case, the act of reading the latest version shouldn't need to import at all.  So, only upserting data with versioning enabled would require py3.  Given that the feature will (at least initially) be opt-in, this seems ok.

Arvid, thoughts?

**Comment by ArvidJB** [comment]
I think in this case we should make the versioned_hdf5 import lazy. I would not even bother with adding reading support to Py2, we just need to make sure that we generate a useful error message which urges people to stop using Py2.

**Comment by asmeurer** [comment]
So just to make sure I understand, something like

```py
# versioned_hdf5.py

# This is the only top-level name that's part of the versioned_hdf5 "public" API.
class VersionedHDF5File(object):
     def __getattr__(self):
          raise RuntimeError("Versioned HDF5 is not supported in Python 2.")
```

which would be installed in the Python 2 environments (it shouldn't be necessary to do anything with ndindex, unless you are using it directly for something).

It may be a little weird to put something like that on PyPI. That would defer the error about not supporting Python 2 to runtime, whereas currently `python2 -m pip install versioned_hdf5` gives an error at install time.

**Comment by ArvidJB** [comment]
Much simpler than that. In *our* code we will write
```
def foo(self):
    if self.versioned:
        if six.PY2:
            raise NotImplementedError('Versioned HDF5 files are only supported in PY3')
        from versioned_hdf5 import VersionedHDF5File
```

**Comment by asmeurer** [comment]
Yes, that should work too. You mentioned you wanted at least `import versioned_hdf5` to work, so if you want that, my example is how I would achieve it. If you're willing to move even the imports to compatibility blocks, then it's easier to do because you don't need a shim module.
