### ISSUE TITLE
Some way to only run fast tests?

### ISSUE THREAD

**Issue by asmeurer** [deshaw/versioned-hdf5#102]
After https://github.com/deshaw/versioned-hdf5/pull/72, some of the tests take a few minutes to run. Does pytest have some way to tag tests as slow so that you can optionally skip them for local test runs?

**Comment by melissawm** [comment]
[Is this](https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option) what you're looking for?

**Comment by asmeurer** [comment]
What does the @slow decorator normally do? I want them to run by default and only not run with a flag.

**Comment by melissawm** [comment]
Oh got it, you want the opposite of what I understood. I don't know if there's a way of building a `conftest.py` to do that.

**Comment by asmeurer** [comment]
We now run the slowest tests last in the test run, which solves the issues I was having with development.
