### ISSUE TITLE
Support for changing chunk size

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#110]
We have some code which will rewrite a file by

1. deleting the existing dataset
2. recreating the dataset with a different chunk size and initial data

Is it possible to support this in a way that preserves version history?

One idea I had was to add support for versioned versions, i.e., each versioned dataset itself is versioned again. This might be a lot of work, though. Maybe there's a cheaper way to support this?

**Comment by ArvidJB** [comment]
Another option would be to leave this out of scope for versioned_hdf5 altogether: we could just rename the existing '.h5' file and keep track of versions across those files outside of versioned_hdf5 (in "user land").

**Comment by asmeurer** [comment]
Would you want the old versions to keep their original chunks, or would it be acceptable to rechunk all versions of the dataset?

**Comment by ArvidJB** [comment]
I think "rechunking" would probably be prohibitively expensive. Since, if we have accumulated a large number of versions already, you would have to replay the versions to figure out the diffs under the new chunks.

This is low priority, if there are no easy wins here we can just work around it.

**Comment by asmeurer** [comment]
Another workaround would be to use a different group or dataset name within the same versioned file. This is basically what we would have to do for the "versioned data is itself versioned" idea.

**Comment by asmeurer** [comment]
The modify_metadata() function can specify a new chunk size for a dataset. I am going to close this, but if there is any behavior that is still missing, please reopen.
