### ISSUE TITLE
Variable length string support

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#111]
We use the pre-h5py-2.9 method to store variable length strings, http://docs.h5py.org/en/2.8.0/strings.html :
```
In [21]: with h5py.File('foo.h5', 'w') as f:
    ...:     dt = h5py.special_dtype(vlen=bytes)
    ...:     dset = f.create_dataset("name", (10,), dtype=dt, data=np.full(10, 'hello world', dtype='O'))
    ...:
```
but this does not work with versioned_hdf5:
```
In [23]: with h5py.File('foo.h5', 'w') as f:
    ...:     vf = VersionedHDF5File(f)
    ...:     with vf.stage_version('0') as sv:
    ...:         dt = h5py.special_dtype(vlen=bytes)
    ...:         dset = sv.create_dataset("name", shape=(10,), dtype=dt, data=np.full(10, 'hello world', d
    ...: type='O'))
    ...:
```
which fails with
```
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

**Comment by asmeurer** [comment]
We aren't passing the detype around properly. But an issue here is how to handle the fillvalue. The current logic to generate a default fillvalue fails for `dt`.

**Comment by asmeurer** [comment]
Partial fix at https://github.com/deshaw/versioned-hdf5/pull/113

**Comment by asmeurer** [comment]
Do we need to support h5py 2.8 as well? My understanding was that 2.9 was OK. #99

**Comment by ArvidJB** [comment]
We are using 2.9. But our code was written pre 2.9 so it uses the old h5py way to support variable length strings.

**Comment by asmeurer** [comment]
I guess the fillvalue issue is an issue with h5py https://github.com/h5py/h5py/issues/941. h5py sets the fillvalue to b'' automatically if none is passed and that seems to work, so we can work around this. Setting a fillvalue of something other than '' won't work, but I don't think that presently works in base h5py either.

**Comment by asmeurer** [comment]
Fix at https://github.com/deshaw/versioned-hdf5/pull/115. There will be issues if there are other object dtypes supported by h5py, as we need to support each type manually.
