### ISSUE TITLE
Support for boolean masks

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#112]
We will need support for masking by boolean arrays. This
```
In [28]: with h5py.File('foo.h5', 'w') as f:
    ...:     vf = VersionedHDF5File(f)
    ...:     with vf.stage_version('0') as sv:
    ...:         dset = sv.create_dataset("bar", data=np.arange(3))
    ...: with h5py.File('foo.h5', 'r+') as f:
    ...:     vf = VersionedHDF5File(f)
    ...:     print(vf[vf.current_version]['bar'][np.array([True, False, True])])
    ...:
```
fails with
```NotImplementedError: boolean array indices are not yet supported```

**Comment by asmeurer** [comment]
This will also require support in ndindex, similar to #97. It may take longer to get full support for this.

**Comment by asmeurer** [comment]
This is ready for testing using the ndindex branch at https://github.com/Quansight/ndindex/pull/76

**Comment by scopatz** [comment]
@asmeurer - can this be closed now?

**Comment by asmeurer** [comment]
ndindex 1.4 is now out and boolean masks should work if you upgrade to it.
