### ISSUE TITLE
Draft for blog post about Versioned HDF5 in Quansight Labs Blog

### ISSUE THREAD

**Issue by melissawm** [deshaw/versioned-hdf5#127]
You can see a draft for this blog post here:

https://github.com/Quansight-Labs/quansight-labs-site/pull/113

This is supposed to be the first in a series of three blog posts.

**Comment by ArvidJB** [comment]
Post looks good to me, I will run the acknowledgement by our external affairs team to confirm.

**Comment by ArvidJB** [comment]
External affairs has approved the acknowledgement.
