### ISSUE TITLE
Return element instead of shape () array

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#137]
`h5py` seems to have some special case for "single_element" `__getitem__` calls which `versioned_hdf5` currently does not have.
This is some code which currently fails with
```TypeError: len() of unsized object```
but which would work in `h5py`:
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        dtype = h5py.special_dtype(vlen=bytes)
        sv.create_dataset('bar', data=np.array(['aaa'], dtype='O'), dtype=dtype)

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    print(len(vf['0']['bar'][0]))
```

**Comment by asmeurer** [comment]
It looks like it does. I guess this matches NumPy behavior. In general, you can always use `a[()]` to get a scalar and `a[...]` to get an array when `a` is shape `()`.
