### ISSUE TITLE
No chunks on virtual dataset?

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#145]
To work around the missing Python 2 support (see #10) we decided to replicate the reading logic (for the current version only) in Python 2. This works nicely, except that the virtual dataset has no `chunks` property?
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('v1') as sv:
        sv.create_dataset('bar', data=np.arange(5), chunks=(10,))

with h5py.File('foo.h5', 'r') as f:
    vf = VersionedHDF5File(f)
    cv = vf[vf.current_version]
    bar = cv['bar']
    assert np.all(bar[:] == np.arange(5))
    assert bar.chunks == (10,)

    versions = f['_version_data/versions']
    bar = versions[versions.attrs['current_version']]['bar']
    assert np.all(bar[:] == np.arange(5))
    assert bar.chunks == (10,)
```
Is that something that's easy to add? If not, I can add another workaround for that.

**Comment by asmeurer** [comment]
I think it is expected. A virtual dataset can point to many datasets and there's no requirement that they all have the same chunks. 

I can add "chunks" to the attrs of each virtual dataset. Would that be helpful?

**Comment by asmeurer** [comment]
https://github.com/deshaw/versioned-hdf5/pull/147

**Comment by ArvidJB** [comment]
Thanks, that is helpful!
