### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#149]
Could we create a 1.2 release now that #142 and #144 are merged?

**Comment by asmeurer** [comment]
Should we include #147 too?

There are some issues with h5py 3 #148 which may take some time to work out. But we can pin the dependency for now.

**Comment by ArvidJB** [comment]
Yes, let's include #147. I am currently working around it, but it would be good not to have to do that.
#148 is not high priority, I doubt that we will switch to h5py 3 any time soon.
