### ISSUE TITLE
Slow resizing of multidimensional datasets

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#155]
We have some code which roughly does the following:
```
dt = np.dtype('double')

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv.create_dataset('bar', (1, 10, 2),
                          chunks=(600, 2, 4),
                          dtype=dt, data=np.full((1, 10, 2), 0, dtype=dt))

for i in range(1, 100):
    with h5py.File('foo.h5', 'r+') as f:
        vf = VersionedHDF5File(f)
        with vf.stage_version(str(i)) as sv:
            bar = sv['bar']
            bar.resize((1, (i+1) * 10, 2))
            bar[:, -10:, :] = np.full((1, 10, 2), i, dtype=dt)
```
Note that the both the updates and the chunk size are pretty small. On my computer that took about 10 minutes! For only writing 2000 values...

It seems that the performance issues are in `ndindex` functions?

**Comment by asmeurer** [comment]
It looks like fixing https://github.com/Quansight-Labs/ndindex/issues/45 would solve this. It's wasting a lot of time computing indices for chunks that don't have any data.

**Comment by asmeurer** [comment]
It also looks like there are some simple changes I can make in ndindex to improve the performance of some functions.

**Comment by ArvidJB** [comment]
Great, good to hear that this is easy!

**Comment by ArvidJB** [comment]
Here's another instance we ran into today:
```
dt = np.dtype('double')

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv.create_dataset('bar', (2, 15220, 2),
                          chunks=(300, 100, 2),
                          dtype=dt, data=np.full((2, 15220, 2), 0, dtype=dt))

start = time.time()
with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('1') as sv:
        bar = sv['bar']
        bar.resize((3, 15222, 2))
end = time.time()
print(end - start)
```
This took 62 seconds!

**Comment by asmeurer** [comment]
I did a 1.2.1 release of versioned-hdf5 that contains some preliminary performance improvements. I should be able to get some further improvements when I come back next week.

**Comment by asmeurer** [comment]
I am working on further performance improvements now. 

One thing of note about the first example. The (final) array shape is (1, 1000, 2) and the chunk size is (600, 2, 4), meaning the array has 2000 elements and a chunk has 4800 elements, but the array uses 500 chunks. I wonder if the chunk size was instead supposed to be (2, 600, 4). If I use that, the time goes from minutes down to a couple of seconds (either way, I think both times can be reduced even further).

**Comment by ArvidJB** [comment]
Yes, the first example is a bit weird, but that's what our automatic chunk selection algorithm came up with... I am following up on this internally.

For the second example we ended up with a more "correct" chunk size and is still slow. It might be easier for you to focus on this example.

**Comment by asmeurer** [comment]
What are you using for the "more correct" chunk size in the second example? I tried using (3, 10000, 2), which has the same size, and the runtime is down to ~50 ms (it's a little slower than that in the latest releases on first run because of an unnecessary SymPy import, which I am fixing. For now you can get a more realistic time by adding `import sympy` to the top of the script before calling `time.time()`). Even (3, 100, 2) takes 500 ms. Again, I am pretty sure there are still lots of optimizations I can make since I've so far been ignoring performance, so I'm sure I can get that even lower. 

But it seems like the biggest performance issue overall is that number of chunks that any operation needs to process. Due to the design of versioned-hdf5, all chunks are operated separately, since they aren't contiguous in the underlying dataset. Every chunk that is processed requires slower Python operations on top of the fast array operations. It's the difference between running `a[x] = y` 10 times vs. 1000 times, even for the same total amount of data.

**Comment by asmeurer** [comment]
There have been many further performance improvements in https://github.com/deshaw/versioned-hdf5/pull/158 and https://github.com/Quansight-Labs/ndindex/pull/110. Versioned-HDF5 1.2.2 and ndindex 1.5.1 have been released with these fixes. Additionally, both repos now have benchmark suites with airspeed-velocity so we can measure the improvements as well as notice any future regressions. I have published the runs at https://quansight-labs.github.io/ndindex/benchmarks/ and https://deshaw.github.io/versioned-hdf5/benchmarks/index.html. The [`time_resize`](https://deshaw.github.io/versioned-hdf5/benchmarks/index.html#resize.time_resize) and [`time_resize_and_write`](https://deshaw.github.io/versioned-hdf5/benchmarks/index.html#resize.time_resize_and_write) Versioned HDF5 benchmarks are exactly the examples from this issue. There is also `time_resize_hdf5` and `time_resize_and_write_hdf5` which do the same thing in pure h5py for comparison. 

If there are any additional issues with performance, please open a new issue. Based on some profiling, there may still be a few small gains that can be made for these benchmarks, but it is looking like a large chunk of the time is now being taken by h5py itself. In particular, the code for creating a virtual dataset is kind of slow. I haven't looked too deeply into h5py to see if there are any simple ways it could be improved.
