### ISSUE TITLE
Log statistics at exit of stage_version context

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#166]
I think it would be helpful if we could log some statistics after writing each version. So probably at the end of a `stage_version` context?
I would be interested in some information like
```
dataset_name: old_shape -> new_shape, chunk size, number of new raw chunks written, number of chunks reused
```
for every dataset impacted in the transaction.

**Comment by asmeurer** [comment]
Maybe a callback that gets called at the end of the context with the appropriate information (and some helper functions to compute those things)? I don't think the context manager can make any assumptions about what the user's method of logging looks like.

**Comment by ArvidJB** [comment]
Good point. I sort of assume that in Python everyone uses the standard logging framework
https://docs.python.org/3/library/logging.html
Are people using any other frameworks?

**Comment by asmeurer** [comment]
I think there are some alternative frameworks that people use, although I haven't used them myself so I don't know too much about them.

**Comment by magsol** [comment]
@ArvidJB Is this still a priority? If not, should we close this issue, or put it in backlog for future consideration?

**Comment by peytondmurray** [comment]
I like this idea, and have done a lot of work on logging recently in some other projects, so I'd be happy to pick this up.

> I don't think the context manager can make any assumptions about what the user's method of logging looks like.

This is definitely true - we should leave it up to the user to determine how log messages should be handled. [As described in the docs](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) I think it would be fine to emit `INFO` level log messages about file statistics. [These wouldn't by default be seen by the user](https://docs.python.org/3/howto/logging.html#what-happens-if-no-configuration-is-provided) unless they set up a handler to the appropriate logger. For those of us interested in seeing library-level log messages, this could be done with a call to `logging.basicConfig` before staging a new version.

Depending on the information we'd like to print, I think we could get this done in not very much time, maybe 5 hours.
