### ISSUE TITLE
Support changing the chunk size

### ISSUE THREAD

**Issue by asmeurer** [deshaw/versioned-hdf5#17]
If a dataset stabilizes, you might want to use a smaller chunk size for future versions.

**Comment by asmeurer** [comment]
Is the chunk size inherent to a dataset, or is it just a property of how a dataset is read into memory?

**Comment by scopatz** [comment]
It is inherent to the dataset I believe

**Comment by asmeurer** [comment]
OK. So the idea here would be to transparently change the backend raw dataset to a new one. I think this wouldn't be hard. It would mean changing the design a bit. Right now, datasets are referenced by name, but we can use a UUID for the raw datasets and get the correct backend version by looking where the virtual dataset points to. There might be other issues that I'm not foreseeing.

**Comment by quarl** [comment]
Supporting altering chunk size parameters in an **existing** data set is low priority.  Reason: Our software layer above the hdf5 layer already has functionality (we call it "vacuum") which will rewrite the *.h5 file from scratch with optimized parameters.

A more useful long-term feature is heterogeneous chunk sizing within one file.

**Comment by asmeurer** [comment]
Setting the chunk size per-dataset is now supported in versioned-hdf5 master (but each version of a dataset must use the same chunk size as the first version).

**Comment by asmeurer** [comment]
Duplicate of https://github.com/deshaw/versioned-hdf5/issues/110
