### ISSUE TITLE
Fix automatic docs updating on CI

### ISSUE THREAD

**Issue by asmeurer** [deshaw/versioned-hdf5#199]
Our GitHub pages pushing script was on Travis, but Travis is no longer running. We need to migrate it to GitHub Actions.

**Comment by asmeurer** [comment]
I've added gh-pages pushing to the release script. Pushing on CI would be nice, but isn't as important.

**Comment by peytondmurray** [comment]
I can take this one. This is a relatively low-effort task, I'd estimate 5 hours to get this working.

**Comment by peytondmurray** [comment]
Just merged this. Workflow ran successfully: https://github.com/deshaw/versioned-hdf5/actions/runs/5978855433, docs have been automatically built and deployed: https://deshaw.github.io/versioned-hdf5/.
