### ISSUE TITLE
Dataset created without data is not virtual

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#220]
If no data is provided when a Dataset is created then the underlying Dataset is not virtual:
```
In [7]: with h5py.File('/var/tmp/foo.h5', 'w') as f:
   ...:     vf = VersionedHDF5File(f)
   ...:     with vf.stage_version('r0') as sv:
   ...:         data_group = sv.create_group('data')
   ...:         data_group.create_dataset('mask', maxshape=(None, None), chunks=(20, 20), shape=(5, 5),
   ...:             dtype=np.dtype('int8'), fillvalue=0)
   ...:

In [8]: with h5py.File('/var/tmp/foo.h5', 'r') as f:
   ...:     assert f['_version_data/versions/r0/data/mask'].is_virtual
   ...:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-2f7435a4e6d1> in <module>
      1 with h5py.File('/var/tmp/foo.h5', 'r') as f:
----> 2     assert f['_version_data/versions/r0/data/mask'].is_virtual
      3

AssertionError:
```

I ran into this while using `delete_versions`. It seems like this does work without issues everywhere else.

**Comment by asmeurer** [comment]
I think this is something we just have to account for. It is already accounted for in some places in the code but I guess I missed it in delete_versions. It's impossible to create a virtual dataset that doesn't have any references, as far as I can tell. 

Maybe a workaround would be to add a dummy reference to the fillvalue. This could create more problems than it solves, though.

**Comment by ArvidJB** [comment]
I am fine with adding a workaround in `delete_versions`.

That being said, could we not create a raw dataset with exactly one chunk set to fillvalue? And then the versioned dataset would reference that one chunk?
