### ISSUE TITLE
Slice assign not working for multiple dimensions

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#225]
I think this kind of slice access to write data should work (it does in "plain" `h5py`):
```
    with TempDirCtx() as d:
        with h5py.File(d / 'foo.h5', 'w') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version('v0') as sv:
                a = np.random.rand(1, 36, 26, 19)
                sv.create_dataset('bar', data=a, chunks=a.shape, maxshape=(None, None, None, None))
        for i in range(1, 101):
            with h5py.File(d / 'foo.h5', 'r+') as f:
                vf = VersionedHDF5File(f)
                with vf.stage_version('v{i}'.format(i=i)) as sv:
                    sv['bar'].resize((i + 1, 36, 26, 19))
                    a = np.random.rand(1, 36, 26, 19)
                    sv['bar'][i, ...] = a
```
Right now I get the following error
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/slice_assign.py", line 19, in <module>
    sv['bar'][i, ...] = a
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 1104, in __setitem__
    self.dataset.__setitem__(index, value)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 767, in __setitem__
    val = np.broadcast_to(val, idx.newshape(self.shape))
  File "<__array_function__ internals>", line 5, in broadcast_to
  File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/numpy/lib/stride_tricks.py", line 411, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/numpy/lib/stride_tricks.py", line 348, in _broadcast_to
    it = np.nditer(
ValueError: input operand has more dimensions than allowed by the axis remapping
```
Note that I can work around this by using
```
                    sv['bar'][[i], ...] = a
```
so this is not high priority, but I think it should still be supported.

**Comment by asmeurer** [comment]
I didn't realize this behavior exists when I wrote this code. It's sort of a "reverse broadcasting".

The shape of `a` is `(1, 36, 26, 19)` and the shape of `sv['bar']` is `(2, 36, 26, 19)`, meaning the shape of `sv['bar'][1, ...]` is `(36, 26, 19)`. So `a` doesn't actually broadcast to the shape of the array it is being assigned to, but rather "reverse broadcasts" to a broadcast compatible shape with the same dimensions. 

This is something that the NumPy developers have considered deprecating https://github.com/numpy/numpy/pull/10615#issuecomment-920987394. 

I guess I need to figure out the exact semantics for it so I can replicate it in the setitem code. Just using `broadcast_to`, which is what the code does now, isn't good enough. Apparently h5py is also doing it, so maybe I can crib some code from there. 

I'm not sure how closely your example resembles your actual code, but I would suggest working around this by not adding the extra size 1 dimension to the front of `a`, or by removing it when doing the assignment like `sv['var'][1, ...] = a[0]`.
