### ISSUE TITLE
Cut release for latest changes

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#253]
Can we create a new release for the changes for https://github.com/deshaw/versioned-hdf5/issues/244 and https://github.com/deshaw/versioned-hdf5/pull/251 please?

**Comment by ArvidJB** [comment]
Who has access to pypi to update the package? Looking at the Maintainers at
https://pypi.org/project/versioned-hdf5/
it seems only @asmeurer, @melissawm, @scopatz? Can we add myself, @quarl and @peytondmurray?

**Comment by ArvidJB** [comment]
Please add @Exaphis as well.

**Comment by asmeurer** [comment]
I can add people to PyPI, but I need your PyPI usernames (not always the same as GitHub usernames).

**Comment by asmeurer** [comment]
Also let me know if you want people added as "owner" or "maintainer". Maintainers can upload releases but only owners can delete releases or add new maintainers.

**Comment by asmeurer** [comment]
1.3.14 has been pushed with the latest changes.

**Comment by peytondmurray** [comment]
Release published: https://github.com/deshaw/versioned-hdf5/releases/tag/1.3.14. Closing as completed.
