### ISSUE TITLE
Move away from `rever` for releases

### ISSUE THREAD

**Issue by peytondmurray** [deshaw/versioned-hdf5#258]
`rever` is not being actively developed anymore. I think it should be possible to cover most if not all of what `rever` currently does using github actions.

**Comment by peytondmurray** [comment]
Here's what we'll need to implement to replace `rever.xsh`:

- [ ] run tests
- [ ] build docs
- [ ] annotated tag
- [ ] push tag
- [ ] pypi publish
- [ ] publish gh-pages

Some of these are already complete.

**Comment by ArvidJB** [comment]
Is this a prerequisite for #253 or can we still cut a release using rever?

**Comment by peytondmurray** [comment]
Asking @asmeurer about this now.

**Comment by peytondmurray** [comment]
Release https://github.com/deshaw/versioned-hdf5/releases/tag/1.3.14 has been made. Unless plans change, the next release will be made without `rever`.

**Comment by peytondmurray** [comment]
I updated PYPI to add the `pypi_publish.yml` workflow as a trusted publisher. Closing this now as complete.
