### ISSUE TITLE
Detect appends and reuse chunks (PyInf#10777)

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#295]
A lot of our writes are actually just appends to existing data. Currently all appends to a chunk are treated the same as any other update: resizing or changing a single value results in a completely new chunk being written to the raw data.

But for pure appends which we do not change any of the existing values we can do better. Take this example below which ends up creating a new raw chunk for each version written:
```
>>> # THIS CELL WAS AUTO-GENERATED BY PYFLYBY
>>> import h5py
>>> import numpy as np
>>> import shutil
>>> from tempfile       import mkdtemp
>>> from versioned_hdf5 import VersionedHDF5File
>>> # END AUTO-GENERATED BLOCK


>>> d = mkdtemp()


>>> chunks = (10,)
>>> num_updates = 15


>>> with h5py.File(d + '/data.h5', 'w') as f:
...     vf = VersionedHDF5File(f)
...     with vf.stage_version('r01') as sv:
...         sv.create_dataset('values', data=np.array([0]), chunks=chunks)
...     for i in range(2, num_updates + 1):
...         with vf.stage_version(f'r{i:02d}') as sv:
...             sv['values'].resize((i,))
...             sv['values'][:] = np.arange(i)


>>> with h5py.File(d + '/data.h5', 'r') as f:
...     value_raw_data = f['_version_data/values/raw_data']
...     print(value_raw_data[:].reshape((-1,) + value_raw_data.chunks))

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0]
 [ 0  1  2  0  0  0  0  0  0  0]
 [ 0  1  2  3  0  0  0  0  0  0]
 [ 0  1  2  3  4  0  0  0  0  0]
 [ 0  1  2  3  4  5  0  0  0  0]
 [ 0  1  2  3  4  5  6  0  0  0]
 [ 0  1  2  3  4  5  6  7  0  0]
 [ 0  1  2  3  4  5  6  7  8  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [10  0  0  0  0  0  0  0  0  0]
 [10 11  0  0  0  0  0  0  0  0]
 [10 11 12  0  0  0  0  0  0  0]
 [10 11 12 13  0  0  0  0  0  0]
 [10 11 12 13 14  0  0  0  0  0]]


>>> from versioned_hdf5.slicetools import spaceid_to_slice
>>> with h5py.File(d + '/data.h5', 'r') as f:
...     for version in f['_version_data/versions']:
...         if version == '__first_version__':
...             continue
...         values_vds = f['_version_data/versions'][version]['values']
...         chunk_map = ', '.join([f'{spaceid_to_slice(vs.vspace)} -> {spaceid_to_slice(vs.src_space)}' for vs in values_vds.virtual_sources()])
...         print(f'{version}: {chunk_map}')

r01: Tuple(slice(0, 1, 1)) -> Tuple(slice(0, 1, 1))
r02: Tuple(slice(0, 2, 1)) -> Tuple(slice(10, 12, 1))
r03: Tuple(slice(0, 3, 1)) -> Tuple(slice(20, 23, 1))
r04: Tuple(slice(0, 4, 1)) -> Tuple(slice(30, 34, 1))
r05: Tuple(slice(0, 5, 1)) -> Tuple(slice(40, 45, 1))
r06: Tuple(slice(0, 6, 1)) -> Tuple(slice(50, 56, 1))
r07: Tuple(slice(0, 7, 1)) -> Tuple(slice(60, 67, 1))
r08: Tuple(slice(0, 8, 1)) -> Tuple(slice(70, 78, 1))
r09: Tuple(slice(0, 9, 1)) -> Tuple(slice(80, 89, 1))
r10: Tuple(slice(0, 10, 1)) -> Tuple(slice(90, 100, 1))
r11: Tuple(slice(0, 10, 1)) -> Tuple(slice(90, 100, 1)), Tuple(slice(10, 11, 1)) -> Tuple(slice(100, 101, 1))
r12: Tuple(slice(0, 10, 1)) -> Tuple(slice(90, 100, 1)), Tuple(slice(10, 12, 1)) -> Tuple(slice(110, 112, 1))
r13: Tuple(slice(0, 10, 1)) -> Tuple(slice(90, 100, 1)), Tuple(slice(10, 13, 1)) -> Tuple(slice(120, 123, 1))
r14: Tuple(slice(0, 10, 1)) -> Tuple(slice(90, 100, 1)), Tuple(slice(10, 14, 1)) -> Tuple(slice(130, 134, 1))
r15: Tuple(slice(0, 10, 1)) -> Tuple(slice(90, 100, 1)), Tuple(slice(10, 15, 1)) -> Tuple(slice(140, 145, 1))


>>> shutil.rmtree(d)
```

But here we can be more clever since those versions do not fill the chunk completely. We can change the raw chunk by writing past the previous slice's end!

In this case we could just end up using only two raw chunks: `[ 0  1  2  3  4  5  6  7  8  9]` and `[10 11 12 13 14  0  0  0  0  0]`!

It will most likely be impossible to detect general chunk reuse possibilities. But for the special case where a Dataset is resized we can detect if the *last chunk* can be reused by comparing the chunk's slice matching the existing slice.

**Comment by ArvidJB** [comment]
Internal ticket: PyInf#10777.

**Comment by peytondmurray** [comment]
I've been looking into how we can implement this. There are a couple of details here that would be good to discuss:

1. We could implement `.append` and/or `__iadd__` methods for the classes in `wrappers.py` so that appending to data is a separate operation from _setting_ data on a group. Then we'd implement some logic:
    1. Gets the last chunk in the raw dataset and the last slice of the latest version; calculate the remaining space in the dataset.
    2. Write as much as you can from the new data into the last chunk of the raw dataset
    3. If there is more data to write, create a new chunk and write the remaining data as usual
2. We could _detect_ when an append operation makes sense. There's probably a few ways we can do this, but essentially we'd be looking for where the new data overlaps with the last chunk of the old data, then writing the remaining values in the new data that aren't in the raw data.

```
Last slice of latest version:     [ a d a d v a d a b c d e f g h ]
Raw data:                         [ a d a d v a d a b c d e f g h 0 0 0 0 0 ]
New data:                                       [ a b c d e f g h i j ]
                                                  ^               ^-- write these remaining values
                                                 Find where these line up
```

@ArvidJB What are your thoughts about this? Which make sense for your use cases?

**Comment by peytondmurray** [comment]
After further investigation, we could also write into unused parts of the raw data if the new data is smaller than the remaining space in the chunk:

```
Raw data:    [ a a b c d e f g h 0 0 0 0 0 ]
New data:                      [ q r s t ]
                                 └ start writing here, rather than a new chunk
```

---

I think a useful thing to do here would be to keep track of the last-written element in the raw data as an attribute (`last_element` or similar), the same way we do for the `current_version`. Then, I propose 

1. Adding `.append` and `__iadd__` functions to the wrappers to append new values to the raw data. This would simply write a new set of values wherever `last_element` points.
2. Adding logic for automatically detecting appends, though this might be somewhat more difficult. For example, if I have

```
Raw data:       [ a b c d e f g 0 0 0 0 0 ]
New data:             [ d e f g ]
```

I should just be able to get away with not writing anything, instead using `Slice(3, 7, 1)` of the `raw_data` for `Slice(0, 5, 1)` of the new (virtual) dataset. But generally speaking the `raw_data` can be spread across multiple chunks:

```
Raw data:       [ f g h j j k l m n p d e ] [ f g 0 0 0 0 0 0 0 0 0 0 ]
New data:                           [ d e    f g ]
```

In either case, for `new_data` of size `N`, we'd need to search at most `N` values back from `last_element` to detect whether an append is possible.

**Comment by peytondmurray** [comment]
Putting a pause on this for now.
