### ISSUE TITLE
Improve exception when attempting to change dataset options (PyInf#12721)

### ISSUE THREAD

**Issue by li-dan** [deshaw/versioned-hdf5#331]
#321 has an example of the exception "ValueError: Compression options can only be specified for the first version of a dataset". It'd be helpful for user debugging to include the name of the dataset, along with the current compression options and the requested compression options. Same for other dataset options that can't be changed, such as chunking, dtype, and fillvalue.

**Comment by peytondmurray** [comment]
Sounds reasonable, although for completeness we'd probably also want to implement some checking of these options in `versioned_hdf5.wrappers._make_new_dset`. I think the most performant way to check these options is to e.g. query `h5py` for the available compression types at module initialization time, then compare the requested compression to the list of available compression types.

**Comment by li-dan** [comment]
Sorry, I mentioned #321, but I'm really concerned about mistakes in application code where `create_dataset` is inadvertently being called with different sets of options, not bugs in h5py. Even a small change in `write_dataset` to enhance the exception messages would be valuable. I want to guard against

**Comment by li-dan** [comment]
Thanks!
