### ISSUE TITLE
Missing __version__ after move to meson build system (Sys#872347)

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#342]
It seems like the `__version__` property no longer exists in version 1.7.0:
```
In [2]: versioned_hdf5.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 versioned_hdf5.__version__

AttributeError: module 'versioned_hdf5' has no attribute '__version__'
```
I think that's because we moved to meson and removed the versioneer code?

**Comment by peytondmurray** [comment]
Yep, that's correct. We can write a file if necessary, but [`importlib.metadata`](https://docs.python.org/3.12/library/importlib.metadata.html) provides a way to retrieve version information for packages through the standard library:

```python
In [1]: from importlib.metadata import version

In [2]: version('versioned_hdf5')
Out[2]: '1.6.1.dev15+gd6949a6'
```

**Comment by Carreau** [comment]
I believe the canonical way of comparing version nowadays is:

```
from importlib.metadata import version
from packaging.version import parse
parse(version('versioned_hdf5')) > parse('1.6.1')  
```

For example.

It's a bit of boilerplate but should be robust to many cases.

**Comment by peytondmurray** [comment]
I've made a PR to export

```python
from importlib.metadata import version
__version__ = version(__package__)
```

to avoid introducing an external dependency on packaging, leaving it up to the user to parse the version.
