### ISSUE TITLE
Support fancy indexing in InMemoryDataset

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#97]
This code 
```
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv['bar'] = np.arange(10)

with h5py.File('foo.h5', 'r') as f:
    vf = VersionedHDF5File(f)
    print(vf['0']['bar'][[0, 1, 3, 5, 6]])
```
fails with some strange errors, both in master as well as in asmeurer/as_subindex.

It should select the entries at index 0, 1, 3, ...

**Comment by ArvidJB** [comment]
Similarly for writing:
```
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv['bar'] = np.arange(10)

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('1') as sv:
        sv['bar'][[0, 1, 3, 5, 6]] = [-1, -2, -3, -4, -5]
```

**Comment by asmeurer** [comment]
Fancy indexing is something that will need to be added to ndindex. I agree the error should be better. I'll make it so that ndindex at least gives a NotImplementedError for index types that are known to be valid but aren't implemented yet.

**Comment by asmeurer** [comment]
Work on this is started at https://github.com/Quansight/ndindex/pull/65. However, I'm not sure how long it will take to finish.

**Comment by asmeurer** [comment]
This is ready for testing using the ndindex branch at https://github.com/Quansight/ndindex/pull/76.

**Comment by scopatz** [comment]
@asmeurer - Can this be closed now?

**Comment by asmeurer** [comment]
Yes, unless you want to wait for the ndindex release.

**Comment by scopatz** [comment]
Nah, let's close now

**Comment by asmeurer** [comment]
ndindex 1.4 is out and integer array indices should work if you upgrade to it.
